name: GitHub Action Test

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Registry Bun
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Get Bun Cache
              id: bun-cache
              run: echo "CACHEDIR=$(bun pm cache)" >> $GITHUB_OUTPUTS

            - name: Caching Dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.bun-cache.outputs.CACHEDIR }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Build Project
              run: bun run build

            - name: Zipping Artifact
              run: zip -r dist.zip ./dist/*

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: distfile
                  path: dist.zip

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                  name: distfile

            - name: Get Keys
              run: |
                  echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
                  chmod 600 key.pem

            - name: Upload Artifact to EC2 Instance
              run: |
                  scp -i key.pem -o StrictHostKeyChecking=no dist.zip ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu
                  ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "rm -rf ./dist && unzip dist.zip -d /home/ubuntu && rm -rf dist.zip"
                  rm -rf key.pem
