name: GitHub Action Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        types:
            - closed

jobs:
    build:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm install

            - name: Build Project
              run: npm run build

            - name: Zipping Artifact
              run: zip -r dist.zip ./dist/*

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: distfile
                  path: dist.zip

            - name: Get Current Directory
              run: pwd

            - name: Get Current Directory's Folder Structure
              run: ls
    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                  name: distfile

            - name: Get Keys
              run: |
                  echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
                  chmod 600 key.pem

            - name: pwd
              run: pwd

            - name: ls
              run: ls

            - name: Upload Artifact to EC2 Instance
              run: |
                  scp -i key.pem -o StrictHostKeyChecking=no dist.zip ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu
                  ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "unzip dist.zip -d /home/ubuntu && rm -rf dist.zip"
                  rm -rf key.pem
